task 6

diff --git a/0x07-networking_basics/5-is_the_host_on_the_network b/0x07-networking_basics/5-is_the_host_on_the_network
--- a/0x07-networking_basics/5-is_the_host_on_the_network
+++ b/0x07-networking_basics/5-is_the_host_on_the_network
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+# PINGs an IP address
 
 if [ $# -eq 0 ]; then
     echo "Usage: $0 {IP_ADDRESS}"
@@ -10,19 +11,16 @@ ip_address=$1
 echo "PING $ip_address ($ip_address) 56(84) bytes of data."
 
 # Ping the IP address 5 times
-ping_result=$(ping -c 5 $ip_address)
+ping -c 5 "$ip_address"
 
-# Display ping result
-echo "$ping_result"
+# Exit status of ping command
+exit_status=$?
 
-# Extract statistics using grep and awk
-packet_loss=$(echo "$ping_result" | grep -oP "\d+% packet loss")
-time_stats=$(echo "$ping_result" | grep -oP "time \K[^ ]+" | awk '{sum+=$1} END {print "rtt min/avg/max/mdev = " sum/NR " ms"}')
-
-# Display statistics based on the result
-if [[ $packet_loss == "0% packet loss" ]]; then
+# Display statistics based on exit status
+if [ $exit_status -eq 0 ]; then
     echo -e "\n--- $ip_address ping statistics ---"
-    echo "5 packets transmitted, 5 received, $packet_loss, $time_stats"
+    echo "5 packets transmitted, 5 received, 0% packet loss, time $(ping -c 5 -W 1 "$ip_address" | grep -oP "time \K[^ ]+" | awk "{print $1}")ms"
+    echo "rtt min/avg/max/mdev = $(ping -c 5 "$ip_address" | tail -n 1 | grep -oP "(\d+\.\d+)/(\d+\.\d+)/(\d+\.\d+)/(\d+\.\d+)" | awk "{print $1 '/' $2 '/' $3 '/' $4}") ms"
 else
     echo -e "\n--- $ip_address ping statistics ---"
     echo "5 packets transmitted, 0 received, 100% packet loss"
